# Generated by Django 5.1.3 on 2025-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
