# Generated by Django 5.1.3 on 2025-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='disease_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Condition Requiring Blood'),
        ),
    ]
