# Generated by Django 5.1.3 on 2025-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
